<a href="https://colab.research.google.com/github/Yunho-seo/education_center5/blob/main/11_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)
print(np.eye(5))  # 단위행렬
np.identity(5)    # +의 항등원 : 0, *의 항등원 : 1, 행렬의 항등원 : 단위행렬렬

1.22.4
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# n차원 행렬 == 다차원 행렬
# 행 우선 : C-Style , 열 우선 : Fortran
#  ndarray : NumPy의 N차원 배열 객체
first = np.ndarray(shape=(2, 2), dtype=float, order='F')  # numpy는 행, 열 어떤 것이던지 사용이 가능하다.
first.fill(10)
first

array([[10., 10.],
       [10., 10.]])

In [5]:
# for문 뒤에 range(시작값, 종료값, 증감값)
# for( 초기값, 한계값, 증감값 )
print(np.arange(10))  # ndarray를 리턴한다.
array = np.arange(10).reshape(5, 2)
print('원배열 : \n', array)

b = np.ones_like(array, float)  # 차수만 빌려 온다.
print('\n동일 사이즈행렬 : \n', b)

array = np.arange(8)
c = np.ones_like(array)  # 1로 채움
print('\nMatrix c : \n', c)

[0 1 2 3 4 5 6 7 8 9]
원배열 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

동일 사이즈행렬 : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Matrix c : 
 [1 1 1 1 1 1 1 1]


In [7]:
c = np.arange(10)
print(c)
print(type(c))   # 타입
c_copy = c[0:5]  # slice 부분집합 (뒤는 포함되지 않음) (0~4)
print(c_copy)

c_copy[0:2] = 100
print(c)
print(c_copy)  # 원본이 수정

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4]
[100 100   2   3   4   5   6   7   8   9]
[100 100   2   3   4]


In [8]:
e = np.arange(24).reshape(2, 3, 4)  # (면, 행, 열) => 2면 3행 4열 : 3x4 행렬이 2개 있다.
print(e)
print(e.flatten())  # flatten() : 1차원으로 변형
e = np.arange(24).reshape(1, 2, 3, 4)  # 차원수의 확장
print('차원 확대')
print(e)
print('차원 축소')

e = e.reshape(-1, 4)  # -1 : 나머지 다 / 4차원을 2차원으로 바꾸기
print(e)
print(e[1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
차원 확대
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]
차원 축소
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[4 5 6 7]


In [9]:
def pprint(arr):
  print("type:{}".format(type(arr)))
  #       차수                 차원                    데이터타입   (배열의 3대 요소)
  print(f"shape : {arr.shape}, dimension : {arr.ndim}, dtype : {arr.dtype}")
  print("배열 데이터:\n", arr)
arr = [1, 2, 3]
a = np.array([1, 2, 3])  # 리스트(list)로 데이터 생성
pprint(a)

type:<class 'numpy.ndarray'>
shape : (3,), dimension : 1, dtype : int64
배열 데이터:
 [1 2 3]


In [20]:
a = np.arange(10)
print(type(a))
print(a.dtype)  # 데이터 자료형 
print(a.shape)  # 차수
print(a.ndim)   # 차원수 (1차원)
print("바이트오더", a.dtype.byteorder)    # 변화 : big endian, little endian
print("아이템 사이즈", a.dtype.itemsize)  # 데이터의 바이트 수 (1바이트는 8비트, 8바이트는 64비트)
print("타입의 이름", a.dtype.type)
print(a.size)  # a의 사이즈 : 10 (개수)
print(a.astype(np.float32))  # 타입을 바꿀 수 있다.
print(a.dtype.itemsize * a.size)  #  메모리 용량 (80 바이트)

<class 'numpy.ndarray'>
int64
(10,)
1
바이트오더 =
아이템 사이즈 8
타입의 이름 <class 'numpy.int64'>
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
80


In [23]:
# [[1, 2], [3, 4]]
# 문제
# 다음 2차원 리스트를 ndarray로 변환하기

list = [[1, 2], [3, 4]]
array = np.array(list)

print(array)
print(type(array))

# np.array([[1, 2], [3, 4]])

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [26]:
# 문제
# 다음 데이터를 arange를 이용하여 작성하기
# a = np.array([[11, 12, 13, 14, 15],
#               [16, 17, 18, 19, 20],
#               [21, 22, 23, 24, 25],
#               [26, 27, 28, 29, 30],
#               [31, 32, 33, 34, 35]])

a = np.arange(11, 36).reshape(5, 5)    
print(a.shape)
print(a)

(5, 5)
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [29]:
# 전치
a.transpose()  # 변환 데이터를 리턴 (원본을 변경하지 않는다)

array([[11, 16, 21, 26, 31],
       [12, 17, 22, 27, 32],
       [13, 18, 23, 28, 33],
       [14, 19, 24, 29, 34],
       [15, 20, 25, 30, 35]])

In [31]:
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [40]:
# 인덱싱 (Indexing)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 3x3 행렬 
print(arr2d.dtype)  # int64(비트)가 디폴트(Default) : 8바이트 
print(arr2d)
print(arr2d[:2])    # 처음 행렬부터 두번째 행렬까지 (0~1)
print()
print(arr2d[0])     # 첫번째 행렬
print(arr2d[0][2])  # 첫번째 행렬의 [2]번 요소
print(arr2d[0, 2])  # arr2d[0][2]와 같음 
print()
print(arr2d[:2])
print(arr2d[:2, 1:])
print(arr2d[1, :2])  # [1]번째 행렬에서 0~1번째 요소
print(arr2d[2, :1])  # [2]번째 행렬에서 0번째 요소
print()
arr2d[:2, :1] = 0    # update
arr2d[:2, :1] = 0
print()
print(arr2d)
print(arr2d.ndim)    # 차원 수
print(arr2d.strides) # 24, 8  # 다음 행이 나오려면 24바이트를 지나가야 하고, 다음 열이 나오려면 8바이트를 지나가야 함
# 데이터는 메모리에 1차원으로 저장

int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]

[1 2 3]
3
3

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[7]


[[0 2 3]
 [0 5 6]
 [7 8 9]]
2
(24, 8)


In [45]:
# 요소 연산과 내적
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])

print(a+b, '\n')
print(a*b, '\n')
print(a.dot(b))  # 내적 / 행렬곱은 내적의 연속이다. 앞에 있는 행벡터를 뒤에 있는 열벡터의 숫자만큼 특성을 추출 

[[5 5]
 [5 5]] 

[[4 6]
 [6 4]] 

[[ 8  5]
 [20 13]]


In [49]:
arr3d = np.arange(1, 13).reshape(2, 2, 3)  # 1부터 12까지, 2면 2x3 행렬 / [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
print(arr3d)
print('첫면은', arr3d[0])  # 0면 
print('첫면 첫행은 =', arr3d[0][0])
print('첫면 첫행, 첫요소는 =', arr3d[0][0][0])

# 문제
# 위 데이터의 차원, 차수, 데이터타입, strides를 확인하기
arr3d.ndim
arr3d.shape
arr3d.dtype
arr3d.strides


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
첫면은 [[1 2 3]
 [4 5 6]]
첫면 첫행은 = [1 2 3]
첫면 첫행, 첫요소는 = 1


(48, 24, 8)

In [50]:
old_values = arr3d.copy()  # 명시적으로 복사
arr3d[0] = 42
print('값의 변경 후')
print(arr3d)
print('이전 값으로 복구')
arr3d = old_values
print(arr3d)

값의 변경 후
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
이전 값으로 복구
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
Z = np.arange(36)
print(Z)
Z = Z.reshape((6, 6))  # 6x6 행렬
print(Z[1:5, 1:5])  # 1부터 4까지 / 교차지점을 선택
print(Z[[1, 2, 3], [1, 2, 3]])  # 7, 14, 21 : 1x1, 2x2, 3x3  # 순서대로 두개씩 짝을 지어서 인덱싱한다. # 리스트를 지정할 때에는 짝이 맞아야 함
A = Z[1:5, 1:5]  # slicing view # 복사할 때에는 명시적으로 .copy를 달아 주저야 함
A[0, 0] = 9
print( A)
print(Z)  # 0 ~ 35

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]
[ 7 14 21]
[[ 9  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]
[[ 0  1  2  3  4  5]
 [ 6  9  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [62]:
arr = np.arange(32).reshape((8, 4))  # 0부터 31까지, 8x4 행렬
print(arr)
print(arr[0, 3])  # 0번째 행렬에서 [3]번째 요소
print(arr[0:2, 0:2])  # 0행부터 1행까지, 1번째에서 2번째 요소만 출력
print("조합 인덱스")
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])  # 1행의 0번, 5행의 3번, 7행의 1번, 2행의 2번

print("파이프")
print(arr[[1, 5, 7, 2]][[0, 3, 1]])  # [1, 5, 7, 2] 중 [0], [3], [1]번째 요소 => 1, 2, 5

print("팬시")
print(arr[[1, 2, 5, 7]][:, [0, 1, 2, 3]])  # [1, 5, 7, 2] 중 행은 전체, 0번째, 1번째, 2번째, 3번째 열
print(arr[[1, 5, 7, 2]][:, [0, 3, 1]])     # [1, 5, 7, 2] 중 행은 전체, 0번째 열, 3번째 열, 1번째 열

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
3
[[0 1]
 [4 5]]
조합 인덱스
[ 4 23 29 10]
파이프
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]
팬시
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5]
 [20 23 21]
 [28 31 29]
 [ 8 11  9]]


In [79]:
# 문제
arr = np.arange(60).reshape((6,10))
a = arr[:, 0:6]
print(a)

# [2, 22, 52] 추출 (빨간색)
print(a[[0, 2, 5], [2, 2, 2]])

# [1, 12, 23, 34, 45] 추출 (주황색)
print(arr[[0,1,2,3,4],[1,2,3,4,5]])

# [[30, 40, 50], [32, 42, 52], [35, 45, 55]] 추출 (파란색)
print(arr[[3, 4, 5]][:, [0, 2, 5]])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[ 2 22 52]
[ 1 12 23 34 45]
[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [80]:
# 문제 (선생님 답)
# 프로그래밍은 늘 규칙과 경우의 수를 찾아야 한다.
arr = []
for i in range(6):
  ad = []
  for j in range(6):
    ad.append(i * 10 + j)
  arr.append(ad)
print(arr)
arr = np.array(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


In [81]:
a = np.arange(0, 6)
arr = np.array([a, a+10, a+20, a+30, a+40, a+50])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [88]:
# 주황색 : [1, 12, 23, 34, 45] 추출
print('주황색', arr[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5]])

# 빨강색 : [2, 22, 52] 추출
print('빨강색', arr[[0, 2, 5], [2, 2, 2]])
# 브로드캐스팅 (broadcasting)
print('빨강색', arr[[0, 2, 5], 2])

# masking(boolean indexing)
mask = np.array([1, 0, 1, 0, 0, 1], dtype = bool)
print(arr[mask, 2])
print(arr[[1, 0, 1, 0, 0, 1], 2])

# 파란색 (팬시로 찾기)
print('파란색(팬시로 찾기)', arr[3:6][:, [0, 2, 5]])

주황색 [ 1 12 23 34 45]
빨강색 [ 2 22 52]
빨강색 [ 2 22 52]
[ 2 22 52]
[12  2 12  2  2 12]
파란색(팬시로 찾기) [[30 32 35]
 [40 42 45]
 [50 52 55]]
